export const width = 1200, height = 600;
export const slider_width = 500, slider_height = 100;
export const padding = 40;
export const margin = {top: 20, right: 80, bottom: 30, left: 70};


export let current_year_global = {year: '1978-1982'};


export const years = {
    1978: '1978-1982',
    1983: '1983-1987',
    1988: '1988-1992',
    1993: '1993-1997',
    1998: '1998-2002',
    2003: '2003-2007',
    2008: '2008-2012',
    2013: '2013-2017',
    2018: '2020',
    2030: '2030',
    2040: '2040',
};

export const display_country = {
    'Afghanistan': {display: false},
    'Albania': {display: false},
    'Algeria': {display: false},
    'Angola': {display: false},
    'Argentina': {display: false},
    'Armenia': {display: false},
    'Australia': {display: false},
    'Austria': {display: false},
    'Azerbaijan': {display: false},
    'Bahrain': {display: false},
    'Bangladesh': {display: false},
    'Belarus': {display: false},
    'Belgium': {display: false},
    'Belize': {display: false},
    'Benin': {display: false},
    'Bhutan': {display: false},
    'Bolivia': {display: false},
    'Bosnia-and-Herzegovina': {display: false},
    'Botswana': {display: false},
    'Brazil': {display: false},
    'Brunei': {display: false},
    'Bulgaria': {display: false},
    'Burkina-Faso': {display: false},
    'Burundi': {display: false},
    'Cambodia': {display: false},
    'Cameroon': {display: false},
    'Canada': {display: false},
    'Central-African-Republic': {display: false},
    'Chad': {display: false},
    'Chile': {display: false},
    'China': {display: false},
    'Colombia': {display: false},
    'Congo': {display: false},
    'Costa-Rica': {display: false},
    'Croatia': {display: false},
    'Cuba': {display: false},
    'Czech-Republic': {display: false},
    'North-Korea': {display: false},
    'Republic-of-the-Congo': {display: false},
    'Denmark': {display: false},
    'Djibouti': {display: false},
    'Dominican-Republic': {display: false},
    'Ecuador': {display: false},
    'Egypt': {display: false},
    'El-Salvador': {display: false},
    'Equatorial-Guinea': {display: false},
    'Eritrea': {display: false},
    'Estonia': {display: false},
    'Ethiopia': {display: false},
    'Finland': {display: false},
    'France': {display: false},
    'Gabon': {display: false},
    'Gambia': {display: false},
    'Georgia': {display: false},
    'Germany': {display: false},
    'Ghana': {display: false},
    'Greece': {display: false},
    'Guatemala': {display: false},
    'Guinea': {display: false},
    'Guinea-Bissau': {display: false},
    'Guyana': {display: false},
    'Haiti': {display: false},
    'Honduras': {display: false},
    'Hungary': {display: false},
    'Iceland': {display: false},
    'India': {display: false},
    'Indonesia': {display: false},
    'Iran': {display: false},
    'Iraq': {display: false},
    'Ireland': {display: false},
    'Israel': {display: false},
    'Italy': {display: false},
    'Japan': {display: false},
    'Jordan': {display: false},
    'Kazakhstan': {display: false},
    'Kenya': {display: false},
    'Kyrgyzstan': {display: false},
    'Laos': {display: false},
    'Latvia': {display: false},
    'Lebanon': {display: false},
    'Lesotho': {display: false},
    'Liberia': {display: false},
    'Libya': {display: false},
    'Lithuania': {display: false},
    'Luxembourg': {display: false},
    'Madagascar': {display: false},
    'Malawi': {display: false},
    'Malaysia': {display: false},
    'Mali': {display: false},
    'Mauritania': {display: false},
    'Mexico': {display: false},
    'Mongolia': {display: false},
    'Morocco': {display: false},
    'Mozambique': {display: false},
    'Myanmar': {display: false},
    'Namibia': {display: false},
    'Nepal': {display: false},
    'Netherlands': {display: false},
    'New-Zealand': {display: false},
    'Nicaragua': {display: false},
    'Niger': {display: false},
    'Nigeria': {display: false},
    'Norway': {display: false},
    'Palestine': {display: false},
    'Oman': {display: false},
    'Pakistan': {display: false},
    'Panama': {display: false},
    'Papua-New-Guinea': {display: false},
    'Paraguay': {display: false},
    'Peru': {display: false},
    'Philippines': {display: false},
    'Poland': {display: false},
    'Portugal': {display: false},
    'Qatar': {display: false},
    'South-Korea': {display: false},
    'Moldova': {display: false},
    'Romania': {display: false},
    'Russia': {display: false},
    'Rwanda': {display: false},
    'Saudi-Arabia': {display: false},
    'Senegal': {display: false},
    'Serbia': {display: false},
    'Sierra-Leone': {display: false},
    'Slovakia': {display: false},
    'Slovenia': {display: false},
    'Somalia': {display: false},
    'South-Africa': {display: false},
    'South-Sudan': {display: false},
    'Spain': {display: false},
    'Sri-Lanka': {display: false},
    'Sudan': {display: false},
    'Suriname': {display: false},
    'Swaziland': {display: false},
    'Sweden': {display: false},
    'Switzerland': {display: false},
    'Syria': {display: false},
    'Tajikistan': {display: false},
    'Thailand': {display: false},
    'Macedonia': {display: false},
    'Timor-Leste': {display: false},
    'Togo': {display: false},
    'Tunisia': {display: false},
    'Turkey': {display: false},
    'Turkmenistan': {display: false},
    'Uganda': {display: false},
    'Ukraine': {display: false},
    'United-Arab-Emirates': {display: false},
    'United-Kingdom': {display: false},
    'United-Republic-of-Tanzania': {display: false},
    'United-States-of-America': {display: false},
    'Uruguay': {display: false},
    'Uzbekistan': {display: false},
    'Venezuela': {display: false},
    'Vietnam': {display: false},
    'Yemen': {display: false},
    'Zambia': {display: false},
    'Zimbabwe': {display: false}
};


export const contents = ['Asia', 'Europe', 'Oceania', 'North America', 'South America', 'Africa'];


const colour_scheme_for_region = {
    'Asia': '#FF0000',
    'Europe': '#FFFF00',
    'Oceania': '#80FF00',
    'North America': '#0000FF',
    'South America': '#CC00CC'
};

// export const country_contents = {
//     'Afghanistan': 'Asia',
//     'Albania': 'Europe',
//     'Algeria': 'Africa',
//     'Angola': 'Africa',
//     'Argentina': 'South America',
//     'Armenia': 'Asia',
//     'Australia': 'Oceania',
//     'Austria': 'Europe',
//     'Azerbaijan': 'Asia',
//     'Bahrain': 'Asia',
//     'Bangladesh': 'Asia',
//     'Belarus': 'Europe',
//     'Belgium': 'Europe',
//     'Belize': 'North America',
//     'Benin': 'Africa',
//     'Bhutan': 'Asia',
//     'Bolivia': 'South America',
//     'Bosnia-and-Herzegovina': 'Europe',
//     'Botswana': 'Africa',
//     'Brazil': 'South America',
//     'Brunei': 'Asia',
//     'Bulgaria': 'Europe',
//     'Burkina-Faso': 'Africa',
//     'Burundi': 'Africa',
//     'Cambodia': 'Asia',
//     'Cameroon': 'Africa',
//     'Canada': 'North America',
//     'Central-African-Republic': 'Africa',
//     'Chad': 'Africa',
//     'Chile': 'South America',
//     'China': 'Asia',
//     'Colombia': 'South America',
//     'Congo': 'Africa',
//     'Costa-Rica': 'North America',
//     'Croatia': 'Europe',
//     'Cuba': 'North America',
//     'Czech-Republic': 'Europe',
//     'Republic-of-the-Congo': 'Africa',
//     'Denmark': 'Europe',
//     'Djibouti': 'Africa',
//     'Dominican-Republic': 'North America',
//     'Ecuador': 'South America',
//     'Egypt': 'Africa',
//     'El-Salvador': 'North America',
//     'Equatorial-Guinea': 'Africa',
//     'Eritrea': 'Africa',
//     'Estonia': 'Europe',
//     'Ethiopia': 'Africa',
//     'Finland': 'Europe',
//     'France': 'Europe',
//     'Gabon': 'Africa',
//     'Gambia': 'Africa',
//     'Georgia': 'Asia',
//     'Germany': 'Europe',
//     'Ghana': 'Africa',
//     'Greece': 'Europe',
//     'Guatemala': 'North America',
//     'Guinea': 'Africa',
//     'Guinea-Bissau': 'Africa',
//     'Guyana': 'South America',
//     'Haiti': 'North America',
//     'Honduras': 'North America',
//     'Hungary': 'Europe',
//     'Iceland': 'Europe',
//     'India': 'Asia',
//     'Indonesia': 'Asia',
//     'Iran': 'Asia',
//     'Iraq': 'Asia',
//     'Ireland': 'Europe',
//     'Israel': 'Asia',
//     'Italy': 'Europe',
//     'Japan': 'Asia',
//     'Jordan': 'Asia',
//     'Kazakhstan': 'Asia',
//     'Kenya': 'Africa',
//     'Kyrgyzstan': 'Asia',
//     'Laos': 'Asia',
//     'Latvia': 'Europe',
//     'Lebanon': 'Asia',
//     'Lesotho': 'Africa',
//     'Liberia': 'Africa',
//     'Libya': 'Africa',
//     'Lithuania': 'Europe',
//     'Luxembourg': 'Europe',
//     'Macedonia': 'Europe',
//     'Madagascar': 'Africa',
//     'Malawi': 'Africa',
//     'Malaysia': 'Asia',
//     'Mali': 'Africa',
//     'Mauritania': 'Africa',
//     'Mexico': 'North America',
//     'Moldova': 'Europe',
//     'Mongolia': 'Asia',
//     'Morocco': 'Africa',
//     'Mozambique': 'Africa',
//     'Myanmar': 'Asia',
//     'Namibia': 'Africa',
//     'Nepal': 'Asia',
//     'Netherlands': 'Europe',
//     'New-Zealand': 'Oceania',
//     'Nicaragua': 'North America',
//     'Niger': 'Africa',
//     'Nigeria': 'Africa',
//     'North-Korea': 'Asia',
//     'Norway': 'Europe',
//     'Oman': 'Asia',
//     'Pakistan': 'Asia',
//     'Palestine': 'Asia',
//     'Panama': 'North America',
//     'Papua-New-Guinea': 'Oceania',
//     'Paraguay': 'South America',
//     'Peru': 'South America',
//     'Philippines': 'Asia',
//     'Poland': 'Europe',
//     'Portugal': 'Europe',
//     'Qatar': 'Asia',
//     'Romania': 'Europe',
//     'Russia': 'Europe',
//     'Rwanda': 'Africa',
//     'Saudi-Arabia': 'Asia',
//     'Senegal': 'Africa',
//     'Serbia': 'Europe',
//     'Sierra-Leone': 'Africa',
//     'Slovakia': 'Europe',
//     'Slovenia': 'Europe',
//     'Somalia': 'Africa',
//     'South-Africa': 'Africa',
//     'South-Korea': 'Asia',
//     'South-Sudan': 'Africa',
//     'Spain': 'Europe',
//     'Sri-Lanka': 'Asia',
//     'Sudan': 'Africa',
//     'Suriname': 'South America',
//     'Swaziland': 'Africa',
//     'Sweden': 'Europe',
//     'Switzerland': 'Europe',
//     'Syria': 'Asia',
//     'Tajikistan': 'Asia',
//     'United-Republic-of-Tanzania': 'Africa',
//     'Thailand': 'Asia',
//     'Timor-Leste': 'Asia',
//     'Togo': 'Africa',
//     'Tunisia': 'Africa',
//     'Turkey': 'Asia',
//     'Turkmenistan': 'Asia',
//     'Uganda': 'Africa',
//     'Ukraine': 'Europe',
//     'United-Arab-Emirates': 'Asia',
//     'United-Kingdom': 'Europe',
//     'United-States-of-America': 'North America',
//     'Uruguay': 'South America',
//     'Uzbekistan': 'Asia',
//     'Venezuela': 'South America',
//     'Vietnam': 'Asia',
//     'Yemen': 'Asia',
//     'Zambia': 'Africa',
//     'Zimbabwe': 'Africa',
// };


export const country_contents = {
    "Africa": {values: ["Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina-Faso",
        "Burundi",
        "Cameroon",
        "Central-African-Republic",
        "Chad",
        "Congo",
        "Republic-of-the-Congo",
        "Djibouti",
        "Egypt",
        "Equatorial-Guinea",
        "Eritrea",
        "Ethiopia",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "Senegal",
        "Sierra-Leone",
        "Somalia",
        "South-Africa",
        "South-Sudan",
        "Sudan",
        "Swaziland",
        "United-Republic-of-Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Zambia",
        "Zimbabwe"], display: false},

    "Europe": {values:  ["Albania",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia-and-Herzegovina",
        "Bulgaria",
        "Croatia",
        "Czech-Republic",
        "Denmark",
        "Estonia",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Hungary",
        "Iceland",
        "Ireland",
        "Italy",
        "Latvia",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Moldova",
        "Netherlands",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Ukraine",
        "United-Kingdom"], display: false},

    "Asia": {values:  ["Afghanistan",
        "Armenia",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Bhutan",
        "Brunei",
        "Cambodia",
        "China",
        "Georgia",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kyrgyzstan",
        "Laos",
        "Lebanon",
        "Malaysia",
        "Mongolia",
        "Myanmar",
        "Nepal",
        "North-Korea",
        "Oman",
        "Pakistan",
        "Palestine",
        "Philippines",
        "Qatar",
        "Saudi-Arabia",
        "South-Korea",
        "Sri-Lanka",
        "Syria",
        "Tajikistan",
        "Thailand",
        "Timor-Leste",
        "Turkey",
        "Turkmenistan",
        "United-Arab-Emirates",
        "Uzbekistan",
        "Vietnam",
        "Yemen"], display: false},

    "North America": {values:  ["Belize",
        "Canada",
        "Costa-Rica",
        "Cuba",
        "Dominican-Republic",
        "El-Salvador",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Mexico",
        "Nicaragua",
        "Panama",
        "United-States-of-America"], display: false},

    "South America": {values: ["Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela",
    ], display: false},

    "Oceania": {values: ["Australia",
        "New-Zealand",
        "Papua-New-Guinea"], display: false}


};

